# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'library.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_MainWindow(object):
    def __init__(self):
        self._book=''

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(416, 250)
        MainWindow.setMinimumSize(QtCore.QSize(400, 250))
        MainWindow.setMaximumSize(QtCore.QSize(600, 250))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.l1 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.l1.setFont(font)
        self.l1.setObjectName("l1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.l1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.line)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.l2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.l2.setFont(font)
        self.l2.setObjectName("l2")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.l2)
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.btn2.setFont(font)
        self.btn2.setAutoFillBackground(True)
        self.btn2.setStyleSheet("")
        self.btn2.setObjectName("btn2")
        self.btn2.clicked.connect(self.total_cost)
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.btn2)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.btn1.setFont(font)
        self.btn1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn1.setStyleSheet("")
        self.btn1.setObjectName("btn1")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btn1)
        self.btn1.clicked.connect(self.get_book) 
        self.er1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(True)
        font.setItalic(False)
        self.er1.setFont(font)
        self.er1.setStyleSheet("color:red")
        self.er1.setInputMethodHints(QtCore.Qt.ImhNone)
        self.er1.setObjectName("er1")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.er1)
        self.tc = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.tc.setFont(font)
        self.tc.setStyleSheet("color:rgb(85, 85, 255);")
        self.tc.setObjectName("tc")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.tc)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.bp = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.bp.setFont(font)
        self.bp.setStyleSheet("color: rgb(85, 85, 255)")
        self.bp.setObjectName("bp")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.bp)
        self.er2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(True)
        self.er2.setFont(font)
        self.er2.setStyleSheet("color:red")
        self.er2.setObjectName("er2")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.er2)
        self.l2.setEnabled(False)
        self.btn2.setEnabled(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
    

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.l1, self.btn1)
        MainWindow.setTabOrder(self.btn1, self.l2)
        MainWindow.setTabOrder(self.l2, self.btn2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Book Title:"))
        self.label_2.setText(_translate("MainWindow", "Quantity:"))
        self.btn2.setText(_translate("MainWindow", "Total"))
        self.label_6.setText(_translate("MainWindow", "Total Cost:"))
        self.btn1.setText(_translate("MainWindow", "Search"))
        self.er1.setText(_translate("MainWindow", ""))
        self.tc.setText(_translate("MainWindow", "Rs.0"))
        self.label_5.setText(_translate("MainWindow", "Book Price:"))
        self.bp.setText(_translate("MainWindow", "Rs.0"))
        self.er2.setText(_translate("MainWindow", ""))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

    def get_book(self):
        library = sqlite3.connect('library.db')
        book = library.cursor()
        sql = "SELECT * FROM library WHERE title='{}'".format(self.l1.text())
        book.execute(sql)
        try:
            self._book = book.fetchone()
            self.bp.setText('Rs.'+str(self._book[3]))
            self.tc.setText('Rs.'+str(self._book[3]))
            library.close()
            self.l2.setEnabled(True)
            self.btn2.setEnabled(True)
        except:
            self.l2.setEnabled(False)
            self.btn2.setEnabled(False)
            self.er1.setText('Sorry! Not found')
    def set_book(self,quantities,title,author,price):
        """ It is use for insert new book in database
    set_book(quantities,title,author,price)"""
        library = sqlite3.connect('library.db')
        book = library.cursor()
        try:
            book.execute("""
            CREATE TABLE library(
            quantities INTGER,
            title TEXT,
            author TEXT,
            price INTGER
            );""")
            book.execute("INSERT INTO library (quantities,title,author,price) VALUES(?,?,?,?)",(self.quantities,self.title,self.author,self.price))
        except:
                book.execute("INSERT INTO library (quantities,title,author,price) VALUES(?,?,?,?)",(self.quantities,self.title,self.author,self.price))
        library.commit()
        library.close()

    def total_cost(self):
        a=int(self.l2.text())
        if a<= self._book[0]:
            TOTAL_COST=a*int(self._book[3])
            self.tc.setText('Rs.'+str(TOTAL_COST))
        else:
            self.er2.setText('Sorry! Only '+str(self._book[0])+' pices are available.')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
